package yjy.com.accounts.databases;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.text.SimpleDateFormat;

/**
 * Entity mapped to table "ACCOUNT_INFO".
 */
public class AccountInfo {

    private Long id;
    private double cost;
    private int way;
    private int use;
    /** Not-null value. */
    private String remark;
    /** Not-null value. */
    private java.util.Date date;

    public AccountInfo() {
    }

    public AccountInfo(Long id) {
        this.id = id;
    }

    public AccountInfo(Long id, double cost, int way, int use, String remark, java.util.Date date) {
        this.id = id;
        this.cost = cost;
        this.way = way;
        this.use = use;
        this.remark = remark;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public int getWay() {
        return way;
    }

    public void setWay(int way) {
        this.way = way;
    }

    public int getUse() {
        return use;
    }

    public void setUse(int use) {
        this.use = use;
    }

    /** Not-null value. */
    public String getRemark() {
        return remark;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("KEY ID:" + id + "\n");
        stringBuilder.append("COST:" + cost + "\n");
        stringBuilder.append("WAY:" + way + "\n");
        stringBuilder.append("USE:" + use + "\n");
        stringBuilder.append("REMARK:" + remark + "\n");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        stringBuilder.append("DATE:" + sdf.format(date) + "\n");

        return stringBuilder.toString();
    }

}
