package yjy.com.accounts.databases;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import yjy.com.accounts.databases.AccountInfo;

import yjy.com.accounts.databases.AccountInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountInfoDaoConfig;

    private final AccountInfoDao accountInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountInfoDaoConfig = daoConfigMap.get(AccountInfoDao.class).clone();
        accountInfoDaoConfig.initIdentityScope(type);

        accountInfoDao = new AccountInfoDao(accountInfoDaoConfig, this);

        registerDao(AccountInfo.class, accountInfoDao);
    }
    
    public void clear() {
        accountInfoDaoConfig.getIdentityScope().clear();
    }

    public AccountInfoDao getAccountInfoDao() {
        return accountInfoDao;
    }

}
